name: publish manually

on: workflow_dispatch

jobs:
  publish_manually:
    name: Publish Manually
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
#          flutter-version: '3.0.1'
          channel: 'stable'
      - name: Run inject credential
        env:
          CREDENTIAL: ${{ secrets.CREDENTIAL_JSON }}
        run: |
          mkdir -p ~/.pub-cache
          echo $CREDENTIAL > ~/.pub-cache/credentials.json
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: echo "y" | flutter pub publish
