name: publish manually

on: workflow_dispatch

jobs:
  publish_manually:
    name: Publish Manually
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
#          flutter-version: '3.0.1'
          channel: 'stable'
      - name: Run inject credential
        env:
          CREDENTIAL: ${{ secrets.CREDENTIAL_JSON }}
        run: |
        mkdir -p ~/Library/Application\ Support/dart
        cat <<EOF > ~/Library/Application\ Support/dart/pub-credentials.json
        $CREDENTIAL
        EOF
        ln -s ~/Library/Application\ Support/dart/pub-credentials.json credentials.json
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter pub publish
