name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
#          flutter-version: '3.0.1'
          channel: 'stable'
      - env:
          CREDENTIAL: ${{ secrets.CREDENTIAL_JSON }}
      - run: echo $CREDENTIAL >> $PUB_CACHE/credentials.json
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter pub publish
