name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run inject credential
        env:
          CREDENTIAL: ${{ secrets.CREDENTIAL_JSON }}
        run: |
          mkdir -p ~/.pub-cache
          echo $CREDENTIAL > ~/.pub-cache/credentials.json
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: echo "y" | flutter pub publish
